spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootcamp
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    out-of-order: true
  main:
    banner-mode: off

server:
  port: 8080